cache: bundler

before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

jobs:
  include:
    - stage: lint
      language: node_js
      node_js:
        - "node"
      script: npm run eslint
    - stage: test
      language: node_js
      node_js:
        - "node"
      script:
        - "npm run test"
        - "npm run ci:sendCoverage"
    - stage: deploy
      #General Setup
      if: env(PUBLISH) = true
      language: node_js
      node_js:
        - "node"
      #Create Changelog
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - nvm install node
          - npx semantic-release
          - ls -alh
      #Github Releases
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: "CHANGELOG.md"
        skip_cleanup: true
      #NPM publish
      #Github Pages
